project:
  type: website

website: 
  title: "TexHour | Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tmp/latex-math-2023-10-17.qmd
      - tmp/keyboard-2023-10-17.qmd
      - tmp/fractions-2023-10-17.qmd
      - tmp/venn-diagrams-2023-10-17.qmd
      - tmp/set-theory-2023-10-19.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 2


